### ISSUE TITLE
How to work with whole worms from brightfield and transparent background

### ISSUE THREAD

**Issue by PradipWEHI** [scholz-lab/PharaGlow#36]
Hi 

I am trying to use PHARAGLOW to track the whole worms from brightfield. Do I have to change anything (parameters) if my background is transparent? I tried to switch between subtracting values (0 or 1) but failed to find the frames. The example you gave is just for labeled pharynxes which I tried with your demo file and it worked fine in my system. 

Please let me know what to change for transparent background. 

Thanks

**Comment by monikascholz** [comment]
Yes, you will need to adapt the parameters such that the worms are visible in the masked images. 
I am not sure I understand what 'failed to find the frames' means. Could you provide a sample image?
